In [28]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(138, 64)  # 5*5 from image dimension
        self.fc2 = nn.Linear(64, 8)
        self.fc3 = nn.Linear(8, 1)

    def forward(self, x):
        x = torch.flatten(x, 1) # flatten all dimensions except the batch dimension
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.sigmoid(self.fc3(x))
        return x


net = Net()
print(net)

Net(
  (fc1): Linear(in_features=138, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=8, bias=True)
  (fc3): Linear(in_features=8, out_features=1, bias=True)
)


In [24]:
torch.tensor([1,23,42,32,4,23,2])

tensor([ 1, 23, 42, 32,  4, 23,  2])

In [30]:
input = torch.randn(10,138)
out = net(input)
print(out)

tensor([[0.5728],
        [0.5554],
        [0.5667],
        [0.5634],
        [0.5533],
        [0.5583],
        [0.5791],
        [0.5396],
        [0.5633],
        [0.5466]], grad_fn=<SigmoidBackward0>)


In [3]:
net.zero_grad()
out.backward()

In [44]:
output = net(input)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss) 

tensor(2.3862, grad_fn=<MseLossBackward0>)


c:\Users\tangzeyu\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\functional.py:1960: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
c:\Users\tangzeyu\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\loss.py:530: UserWarning: Using a target size (torch.Size([1, 10])) that is different to the input size (torch.Size([10, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [61]:
criterion = nn.CrossEntropyLoss()
criterion(x, y)

tensor(1.0455)

In [55]:
criterion(torch.tensor([[0.01]]), torch.tensor([[0.6]]))

tensor(-0.)

In [60]:
x = torch.rand((3,3))
y = torch.tensor([0,1,1])

In [58]:
x,y

(tensor([[0.8216, 0.5941, 0.2923],
         [0.7643, 0.7407, 0.3409],
         [0.2788, 0.9287, 0.2757]]),
 tensor([0, 1, 1]))

In [14]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

loss.backward()

In [15]:
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()    # Does the update

In [10]:
import torch.nn as nn
import torch

x = torch.rand((3,3))
y = torch.tensor([0,1,1])

x


tensor([[0.6043, 0.3868, 0.5582],
        [0.6964, 0.8566, 0.1871],
        [0.3695, 0.9915, 0.5423]])

In [11]:
softmax = nn.Softmax()
x_softmax = softmax(x)

x_softmax


C:\Users\tangzeyu\AppData\Local\Temp\ipykernel_15372\1894274687.py:2: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  x_softmax = softmax(x)


tensor([[0.3624, 0.2915, 0.3461],
        [0.3604, 0.4230, 0.2166],
        [0.2468, 0.4598, 0.2934]])

In [12]:
x_log = torch.log(x_softmax)
x_log

tensor([[-1.0151, -1.2326, -1.0611],
        [-1.0205, -0.8603, -1.5299],
        [-1.3990, -0.7770, -1.2262]])

In [13]:
ls = nn.LogSoftmax(dim=1)
ls(x)

tensor([[-1.0151, -1.2326, -1.0611],
        [-1.0205, -0.8603, -1.5299],
        [-1.3990, -0.7770, -1.2262]])

In [15]:
x_log[range(len(x)),y] 

tensor([-1.0151, -0.8603, -0.7770])

In [14]:
loss = x_log[range(len(x)),y]  #取出每一个样本标签值处的概率
loss = abs(sum(loss)/len(x))
loss

tensor(0.8841)

In [ ]:
import pandas as pd
import os

In [29]:
x = 9
assert x  0

AssertionError: 